replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 3000
  externalPort: 80
ingress:
  enabled: false
  #basedomain: # replace with your own from the portal
