replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 3000
  externalPort: 80
ingress:
  enabled: false
  basedomain: #1d760aad894b4bd69d94.eastus.aksapp.io # replace with your own from the portal
