pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  batch: true
  branches:
    include: 
    - refs/heads/*
  paths:
    include: 
    - parrot/

variables:
  projectName: parrot
  registryServerName: '$(registryName).azurecr.io'
  imageName: '$(projectName)'
  # define 3 more variables: registryName, registryLogin and registryPassword in the build pipeline in UI


steps:
- bash: docker build -f $(system.defaultWorkingDirectory)/$(projectName)/Dockerfile -t $(registryServerName)/$(imageName):$(build.buildId) $(system.defaultWorkingDirectory)/$(projectName)
  displayName: 'docker build'

- bash: |
    docker login $(registryServerName) -u $(registryLogin) -p $(registryPassword)
    docker push $(registryServerName)/$(imageName):$(build.buildId)
  displayName: 'docker push'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

- task: HelmInstaller@0
  displayName: 'Install Helm'
  inputs:
    helmVersion: 2.14.1

- bash: helm plugin install https://github.com/chartmuseum/helm-push
  displayName: install plugin

- bash: helm package --version $(build.buildId) --destination $(build.artifactStagingDirectory) $(system.defaultWorkingDirectory)/$(projectName)/charts/$(projectName)
  displayName: 'helm package'

- bash: helm repo add chartmuseum http://35.243.67.100:8080
  displayName: 'add chartmuseum'

- bash: helm push $(build.artifactStagingDirectory)/$(projectName)-$(build.buildId).tgz chartmuseum
  displayName: 'helm push'

- bash: az acr helm push -n $(registryName) -u $(registryLogin) -p $(registryPassword) $(build.artifactStagingDirectory)/$(projectName)-$(build.buildId).tgz
  displayName: 'az acr helm push'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))